spring.application.name=demo

keycloak.base-url=${KEYCLOAK_BASE_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.auth.client-id=${KEYCLOAK_AUTH_CLIENT_ID}
keycloak.auth.client-secret=${KEYCLOAK_AUTH_CLIENT_SECRET}
keycloak.auth.grant-type=${KEYCLOAK_AUTH_GRANT_TYPE}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
keycloak.admin.grant-type=${KEYCLOAK_ADMIN_GRANT_TYPE}

security.authorization.resource-client-id=${KEYCLOAK_RESOURCE_CLIENT_ID}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.base-url}/realms/${keycloak.realm}
